### PR TITLE
eda script and edited cleanup script

### PR DESCRIPTION
**Pull request by Radascript**
sample-docopt.r script: edited to include data cleanup. Cleaned column titles, dropped unneccesary columns
Created eda.py file which creates tables and figures in appropriate folders. Three tables (info, counts, summary) in data/processed/ and two plots (boxplots, densities) in doc/.

Tested via python eda.py

NOTE: Need help with lines 9-13 of eda.py script - reading processed data into the file. I did it to work locally!!
NOTE: New dependensies:
- altair_saver in python
- library(janitor) in R

### CODE REVIEW

**Review by AraiYuno — CHANGES_REQUESTED** [review]
Take a look at this modified file.

You can see that I have used docopt to merge load in the processed_offender_profile.csv file, and I also specify results folder path to save your output files.

You will have to modify your codes to use the results_folder_path.

Please run the following  command on root folder
`python src/eda.py --processed_data_path="./data/processed/processed_offender_profile.csv" --results_folder_path="./data/results"`


```
"""EDA on processed data (add more description).
Usage: eda.py --processed_data_path=<relative_data_path> --results_folder_path=<relative_folder_path> 

Options:
--processed_data_path=<relative_data_path>     Relative path for processed data
--results_folder_path=<relative_folder_path>   Relative path for all the outputs
"""

import numpy as np
import pandas as pd
import altair as alt
import os
from altair_saver import save
from docopt import docopt

opt = docopt(__doc__)

script_dir = os.path.dirname(__file__) #<-- absolute dir the script is in
rel_path = "processed_offender_profile.csv"
abs_file_path = os.path.join(script_dir, rel_path)

def main(processed_data_path, results_folder_path):

    # df_init = pd.read_csv(abs_file_path)
    df_init = pd.read_csv(processed_data_path)

    print(df_init)

    alt.data_transformers.disable_max_rows() #normally, altair limits it to 5K rows
    alt.renderers.enable('png')

    df = df_init

    #########################
    ########   INFO  ########
    #########################

    # Quick info confirming dtypes and no missing values. 
    # Save it to data/processed folder

    df_info = pd.DataFrame(df.info())
    filename = 'dataset_info.csv'

    dirname = '../data/processed'
    if not os.path.exists(dirname):
        os.mkdir(dirname)

    fullpath_data_info = os.path.join(dirname, filename)
    df_info.to_csv(fullpath_data_info)

    ##########################
    ########   COUNTS  ########
    ##########################

    #Let's take a glance at how many observations we have of each 
    #grouping and save it as csv in data/processed folder

    df_counts = pd.DataFrame(df['race_grouping'].value_counts())
    df_counts = df_counts.rename(columns={"race_grouping": "Count"})

    filename = 'group_counts.csv'

    dirname = '../data/processed'
    if not os.path.exists(dirname):
        os.mkdir(dirname)

    fullpath_counts = os.path.join(dirname, filename)
    df_counts.to_csv(fullpath_counts)


    #####################
    ###### SUMMARY ######
    #####################

    # Let's do min max mean median by group for length of sentence 
    # and save it as csv in data/processed folder

    df_summary = df.groupby('race_grouping').agg({'aggregate_sentence_length': ['mean','median', 'min', 'max']})
    filename = 'basic_summary_table.csv'

    dirname = '../data/processed'
    if not os.path.exists(dirname):
        os.mkdir(dirname)

    fullpath_summary_table = os.path.join(dirname, filename)
    df_summary.to_csv(fullpath_summary_table)

    #######################
    ###### BOX PLOTS ######
    #######################

    # Create box plots and 
    # Save the boxplots to ~/doc/eda-box_plots.png

    ratio_boxplots = alt.Chart(df).mark_boxplot().encode(
        x = alt.X('aggregate_sentence_length', type='quantitative'),
        y = alt.Y('race_grouping'), 
        color = 'race_grouping'
    ).properties(
        height = 350,
        width = 800
    )

    filename = 'eda-box_plots.png'

    dirname = '../doc'
    if not os.path.exists(dirname):
        os.mkdir(dirname)

    fullpath_boxplots = os.path.join(dirname, filename)
    ratio_boxplots.save(fullpath_boxplots)


    #######################
    ###### DENSITIES ######
    #######################

    # Save the densities plot to ~/doc/eda-densities.png

    densities = alt.Chart(df).transform_density(
        'aggregate_sentence_length',
        groupby=['race_grouping'],
        as_=['aggregate_sentence_length', 'density'],
    ).mark_area(
        opacity=0.5,
        clip=True
    ).encode(
        x=alt.X('aggregate_sentence_length', scale=alt.Scale(domain=[700, 5000])),
        y='density:Q',
        color='race_grouping'
    )

    filename = 'eda-densities.png'

    dirname = '../doc'
    if not os.path.exists(dirname):
        os.mkdir(dirname)

    fullpath_densities = os.path.join(dirname, filename)
    densities.save(fullpath_densities)

if __name__ == "__main__":
    main(opt["--processed_data_path"], opt["--results_folder_path"])
```

**Review by AraiYuno — CHANGES_REQUESTED** [review]
Could we perhaps change the name of the file from eda.py to something more descriptive at the very high level.

**Comment by showcy** [comment]
Maybe eda_correctional.py?

**Comment by miyer26** [comment]
The changes look good, can merge

**Comment by AraiYuno** [comment]
@Radascript  Thanks! I can confirm that the changes are perfect

**Pull request merged**
